#!/usr/bin/perl -lw

test() if $ARGV[0] eq '--test';
print main();

sub main {
    my $Words       = "/usr/share/dict/words";
    my $Max_Length  = 8;
    my $Num_Words   = 4;

    my @words;
    open my $fh, "<", $Words or die $!;
    my $count = 0;
    while (my $line = <$fh>) {
        chomp $line;
        $count++;
        if ( $count <= $Num_Words ) {
            $words[$count-1] = $line;
        } elsif ( rand($count) <= $Num_Words ) {
            $words[rand($Num_Words)] = $line;
        }
    }

    return join ".", @words;
}

sub test {
    use Test::More;

    my $output = main();
    my @words = split m{\.}, $output;

    is @words, 4, "output 4 words";

    for my $word (@words) {
        like $word, qr/^\w+$/, "  it is a word";
    }

    done_testing();
    exit;
}

1;
